### ISSUE TITLE
[debug error] m.toString is an invalid function

### ISSUE THREAD

**Issue by ColonelGerdauf** [Break-Ben/BetterDiscordAddons#11]
I keep seeing this spam of errors when BetterDiscord starts up, and I myself am trying to make sense of what the actual root issue is. Below is the chunk of error feedback in the debug logs.

```
[2022-11-07 16:30:22.390][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule]
Module filter threw an exception. m => m.toString().includes('"transitionTo - Transitioning to "')
TypeError: m.toString is not a function
    at getModule.searchExports (betterdiscord://plugins/BetterChatNames.plugin.js:23:39)
    at <anonymous>:4:49624
    at Function.getModule (<anonymous>:4:50381)
    at getModule (<anonymous>:4:405689)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:23:22)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
[2022-11-07 16:30:22.409][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule]
Module filter threw an exception. m => Object.values(m).some(v => v.toString().includes(".SELECTED"))
TypeError: Cannot read property 'toString' of null
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:25:62)
    at Array.some (<anonymous>)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:25:50)
    at <anonymous>:4:49624
    at Function.getModule (<anonymous>:4:50450)
    at getModule (<anonymous>:4:405689)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:25:18)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
[2022-11-07 16:30:22.423][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule]
Module filter threw an exception. m => Object.values(m).some(v => v.toString().includes(".toolbar"))
TypeError: Cannot read property 'toString' of null
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:26:59)
    at Array.some (<anonymous>)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:26:47)
    at <anonymous>:4:49624
    at Function.getModule (<anonymous>:4:50450)
    at getModule (<anonymous>:4:405689)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:26:15)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
[2022-11-07 16:30:22.473][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule]
Module filter threw an exception. m => Object.values(m).some(v => v.toString().includes(".iconMention"))
TypeError: Cannot read property 'toString' of null
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:27:61)
    at Array.some (<anonymous>)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:27:49)
    at <anonymous>:4:49624
    at Function.getModule (<anonymous>:4:50450)
    at getModule (<anonymous>:4:405689)
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:27:17)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)
```

**Comment by Break-Ben** [comment]
Fixed in 0c20a36 (1.4.1)
