### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Rocky712YT** [Break-Ben/BetterDiscordAddons#17]
Current BetterDiscord version without any plugins.

TypeError: Cannot read properties of undefined (reading 'type')
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:30:129)
    at A.requireAddon (betterdiscord/renderer.js:4:35265)
    at A.loadAddon (betterdiscord/renderer.js:4:7766)
    at A.loadAddon (betterdiscord/renderer.js:4:32937)
    at A.reloadAddon (betterdiscord/renderer.js:4:8656)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5792)

**Comment by Break-Ben** [comment]
Already fixed in 2c54ef9 (1.4.7)
